<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="huhu" failures="1" tests="7" name="later in the day" time="0.081" errors="0" timestamp="2021-03-23T18:46:38 CET">
  <testcase classname="TestNG.day2" name="SecondTest" time="0.001"/>
  <testcase classname="TestNG.day2" name="SecondTest" time="0.001"/>
  <testcase classname="TestNG.day2" name="SecondTest" time="0.001"/>
  <testcase classname="TestNG.Basics" name="Demo" time="0.011"/>
  <testcase classname="TestNG.Basics" name="SecondTest" time="0.004"/>
  <testcase classname="TestNG.day3" name="DemoFromTest3" time="0.003">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at TestNG.day3.DemoFromTest3(day3.java:11)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- DemoFromTest3 -->
  <testcase classname="TestNG.day3" name="SecondTest" time="0.0">
    <skipped/>
  </testcase> <!-- SecondTest -->
  <testcase classname="TestNG.day2" name="Demo" time="0.0">
    <ignored/>
  </testcase> <!-- Demo -->
</testsuite> <!-- later in the day -->
